version: "3"
services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379"
    networks:
      - "front-tier"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    image: "postgres:9.4"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - "back-tier"
    deploy:
      placement:
        constraints: [node.role == manager]

  vote:
    image: "dockersamples/examplevotingapp_vote:before"
    ports:
      - "5000:80"
    networks:
      - "front-tier"
    depends_on:
      - "redis"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure